[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'ds-test/=lib/ds-test/src/',
    '@superfluid-finance/=node_modules/@superfluid-finance/',
    '@openzeppelin/=node_modules/@openzeppelin/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config